fileFormatVersion: 2
guid: 84a067b337a41634a9f76fe727d4467d
DefaultImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
AssetOrigin:
  serializedVersion: 1
  productId: 289926
  packageName: Oceanis 2024 Pro URP Water Framework
  packageVersion: 2.3.0
  assetPath: Assets/ARTnGAME/Orion Space Framework/SPECIAL FX/URPLensFlare/Flare
    Textures CC0/flare_20120324/makefile
  uploadId: 902342
